INSERT INTO `currencies` (`id`, `country`, `currency`, `code`, `minor_unit`, `symbol`) VALUES
(null,'Afghanistan', 'Afghani', 'AFN', 2, '؋'),
(null,'Åland Islands', 'Euro', 'EUR', 2, '€'),
(null,'Albania', 'Lek', 'ALL', 2, 'Lek'),
(null,'Algeria', 'Algerian Dinar', 'DZD', 2, NULL),
(null,'American Samoa', 'US Dollar', 'USD', 2, '$'),
(null,'Andorra', 'Euro', 'EUR', 2, '€'),
(null,'Angola', 'Kwanza', 'AOA', 2, NULL),
(null,'Anguilla', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Antigua And Barbuda', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Argentina', 'Argentine Peso', 'ARS', 2, '$'),
(null,'Armenia', 'Armenian Dram', 'AMD', 2, NULL),
(null,'Aruba', 'Aruban Florin', 'AWG', 2, NULL),
(null,'Australia', 'Australian Dollar', 'AUD', 2, '$'),
(null,'Austria', 'Euro', 'EUR', 2, '€'),
(null,'Azerbaijan', 'Azerbaijan Manat', 'AZN', 2, NULL),
(null,'Bahamas', 'Bahamian Dollar', 'BSD', 2, '$'),
(null,'Bahrain', 'Bahraini Dinar', 'BHD', 3, NULL),
(null,'Bangladesh', 'Taka', 'BDT', 2, '৳'),
(null,'Barbados', 'Barbados Dollar', 'BBD', 2, '$'),
(null,'Belarus', 'Belarusian Ruble', 'BYN', 2, NULL),
(null,'Belgium', 'Euro', 'EUR', 2, '€'),
(null,'Belize', 'Belize Dollar', 'BZD', 2, 'BZ$'),
(null,'Benin', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Bermuda', 'Bermudian Dollar', 'BMD', 2, NULL),
(null,'Bhutan', 'Indian Rupee', 'INR', 2, '₹'),
(null,'Bhutan', 'Ngultrum', 'BTN', 2, NULL),
(null,'Bolivia', 'Boliviano', 'BOB', 2, NULL),
(null,'Bolivia', 'Mvdol', 'BOV', 2, NULL),
(null,'Bonaire, Sint Eustatius And Saba', 'US Dollar', 'USD', 2, '$'),
(null,'Bosnia And Herzegovina', 'Convertible Mark', 'BAM', 2, NULL),
(null,'Botswana', 'Pula', 'BWP', 2, NULL),
(null,'Bouvet Island', 'Norwegian Krone', 'NOK', 2, NULL),
(null,'Brazil', 'Brazilian Real', 'BRL', 2, 'R$'),
(null,'British Indian Ocean Territory', 'US Dollar', 'USD', 2, '$'),
(null,'Brunei Darussalam', 'Brunei Dollar', 'BND', 2, NULL),
(null,'Bulgaria', 'Bulgarian Lev', 'BGN', 2, 'лв'),
(null,'Burkina Faso', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Burundi', 'Burundi Franc', 'BIF', 0, NULL),
(null,'Cabo Verde', 'Cabo Verde Escudo', 'CVE', 2, NULL),
(null,'Cambodia', 'Riel', 'KHR', 2, '៛'),
(null,'Cameroon', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Canada', 'Canadian Dollar', 'CAD', 2, '$'),
(null,'Cayman Islands', 'Cayman Islands Dollar', 'KYD', 2, NULL),
(null,'Central African Republic', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Chad', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Chile', 'Chilean Peso', 'CLP', 0, '$'),
(null,'Chile', 'Unidad de Fomento', 'CLF', 4,NULL),
(null,'China', 'Yuan Renminbi', 'CNY', 2, '¥'),
(null,'Christmas Island', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Cocos (keeling) Islands', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Colombia', 'Colombian Peso', 'COP', 2, '$'),
(null,'Colombia', 'Unidad de Valor Real', 'COU', 2, NULL),
(null,'Comoros', 'Comorian Franc ', 'KMF', 0, NULL),
(null,'Congo (the Democratic Republic Of The)', 'Congolese Franc', 'CDF', 2, NULL),
(null,'Congo', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Cook Islands', 'New Zealand Dollar', 'NZD', 2, '$'),
(null,'Costa Rica', 'Costa Rican Colon', 'CRC', 2, NULL),
(null,'Côte D\'ivoire', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Croatia', 'Kuna', 'HRK', 2, 'kn'),
(null,'Cuba', 'Cuban Peso', 'CUP', 2, NULL),
(null,'Cuba', 'Peso Convertible', 'CUC', 2, NULL),
(null,'Curaçao', 'Netherlands Antillean Guilder', 'ANG', 2, NULL),
(null,'Cyprus', 'Euro', 'EUR', 2, '€'),
(null,'Czechia', 'Czech Koruna', 'CZK', 2, 'Kč'),
(null,'Denmark', 'Danish Krone', 'DKK', 2, 'kr'),
(null,'Djibouti', 'Djibouti Franc', 'DJF', 0, NULL),
(null,'Dominica', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Dominican Republic', 'Dominican Peso', 'DOP', 2, NULL),
(null,'Ecuador', 'US Dollar', 'USD', 2, '$'),
(null,'Egypt', 'Egyptian Pound', 'EGP', 2, NULL),
(null,'El Salvador', 'El Salvador Colon', 'SVC', 2, NULL),
(null,'El Salvador', 'US Dollar', 'USD', 2, '$'),
(null,'Equatorial Guinea', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Eritrea', 'Nakfa', 'ERN', 2, NULL),
(null,'Estonia', 'Euro', 'EUR', 2, '€'),
(null,'Eswatini', 'Lilangeni', 'SZL', 2, NULL),
(null,'Ethiopia', 'Ethiopian Birr', 'ETB', 2, NULL),
(null,'European Union', 'Euro', 'EUR', 2, '€'),
(null,'Falkland Islands [Malvinas]', 'Falkland Islands Pound', 'FKP', 2, NULL),
(null,'Faroe Islands', 'Danish Krone', 'DKK', 2, NULL),
(null,'Fiji', 'Fiji Dollar', 'FJD', 2, NULL),
(null,'Finland', 'Euro', 'EUR', 2, '€'),
(null,'France', 'Euro', 'EUR', 2, '€'),
(null,'French Guiana', 'Euro', 'EUR', 2, '€'),
(null,'French Polynesia', 'CFP Franc', 'XPF', 0, NULL),
(null,'French Southern Territories', 'Euro', 'EUR', 2, '€'),
(null,'Gabon', 'CFA Franc BEAC', 'XAF', 0, NULL),
(null,'Gambia', 'Dalasi', 'GMD', 2, NULL),
(null,'Georgia', 'Lari', 'GEL', 2, '₾'),
(null,'Germany', 'Euro', 'EUR', 2, '€'),
(null,'Ghana', 'Ghana Cedi', 'GHS', 2, NULL),
(null,'Gibraltar', 'Gibraltar Pound', 'GIP', 2, NULL),
(null,'Greece', 'Euro', 'EUR', 2, '€'),
(null,'Greenland', 'Danish Krone', 'DKK', 2, NULL),
(null,'Grenada', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Guadeloupe', 'Euro', 'EUR', 2, '€'),
(null,'Guam', 'US Dollar', 'USD', 2, '$'),
(null,'Guatemala', 'Quetzal', 'GTQ', 2, NULL),
(null,'Guernsey', 'Pound Sterling', 'GBP', 2, '£'),
(null,'Guinea', 'Guinean Franc', 'GNF', 0, NULL),
(null,'Guinea-bissau', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Guyana', 'Guyana Dollar', 'GYD', 2, NULL),
(null,'Haiti', 'Gourde', 'HTG', 2, NULL),
(null,'Haiti', 'US Dollar', 'USD', 2, '$'),
(null,'Heard Island And Mcdonald Islands', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Holy See (Vatican)', 'Euro', 'EUR', 2, '€'),
(null,'Honduras', 'Lempira', 'HNL', 2, NULL),
(null,'Hong Kong', 'Hong Kong Dollar', 'HKD', 2, '$'),
(null,'Hungary', 'Forint', 'HUF', 2, 'ft'),
(null,'Iceland', 'Iceland Krona', 'ISK', 0, NULL),
(null,'India', 'Indian Rupee', 'INR', 2, '₹'),
(null,'Indonesia', 'Rupiah', 'IDR', 2, 'Rp'),
(null,'International Monetary Fund (IMF)', 'SDR (Special Drawing Right)', 'XDR', 0, NULL),
(null,'Iran', 'Iranian Rial', 'IRR', 2, NULL),
(null,'Iraq', 'Iraqi Dinar', 'IQD', 3, NULL),
(null,'Ireland', 'Euro', 'EUR', 2, '€'),
(null,'Isle Of Man', 'Pound Sterling', 'GBP', 2, '£'),
(null,'Israel', 'New Israeli Sheqel', 'ILS', 2, '₪'),
(null,'Italy', 'Euro', 'EUR', 2, '€'),
(null,'Jamaica', 'Jamaican Dollar', 'JMD', 2, NULL),
(null,'Japan', 'Yen', 'JPY', 0, '¥'),
(null,'Jersey', 'Pound Sterling', 'GBP', 2, '£'),
(null,'Jordan', 'Jordanian Dinar', 'JOD', 3, NULL),
(null,'Kazakhstan', 'Tenge', 'KZT', 2, NULL),
(null,'Kenya', 'Kenyan Shilling', 'KES', 2, 'Ksh'),
(null,'Kiribati', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Korea (the Democratic People’s Republic Of)', 'North Korean Won', 'KPW', 2, NULL),
(null,'Korea (the Republic Of)', 'Won', 'KRW', 0, '₩'),
(null,'Kuwait', 'Kuwaiti Dinar', 'KWD', 3, NULL),
(null,'Kyrgyzstan', 'Som', 'KGS', 2, NULL),
(null,'Lao People’s Democratic Republic', 'Lao Kip', 'LAK', 2, NULL),
(null,'Latvia', 'Euro', 'EUR', 2, '€'),
(null,'Lebanon', 'Lebanese Pound', 'LBP', 2, NULL),
(null,'Lesotho', 'Loti', 'LSL', 2, NULL),
(null,'Lesotho', 'Rand', 'ZAR', 2, NULL),
(null,'Liberia', 'Liberian Dollar', 'LRD', 2, NULL),
(null,'Libya', 'Libyan Dinar', 'LYD', 3, NULL),
(null,'Liechtenstein', 'Swiss Franc', 'CHF', 2, NULL),
(null,'Lithuania', 'Euro', 'EUR', 2, '€'),
(null,'Luxembourg', 'Euro', 'EUR', 2, '€'),
(null,'Macao', 'Pataca', 'MOP', 2, NULL),
(null,'North Macedonia', 'Denar', 'MKD', 2, NULL),
(null,'Madagascar', 'Malagasy Ariary', 'MGA', 2, NULL),
(null,'Malawi', 'Malawi Kwacha', 'MWK', 2, NULL),
(null,'Malaysia', 'Malaysian Ringgit', 'MYR', 2, 'RM'),
(null,'Maldives', 'Rufiyaa', 'MVR', 2, NULL),
(null,'Mali', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Malta', 'Euro', 'EUR', 2, '€'),
(null,'Marshall Islands', 'US Dollar', 'USD', 2, '$'),
(null,'Martinique', 'Euro', 'EUR', 2, '€'),
(null,'Mauritania', 'Ouguiya', 'MRU', 2, NULL),
(null,'Mauritius', 'Mauritius Rupee', 'MUR', 2, NULL),
(null,'Mayotte', 'Euro', 'EUR', 2, '€'),
(null,'Member Countries Of The African Development Bank Group', 'ADB Unit of Account', 'XUA', 0, NULL),
(null,'Mexico', 'Mexican Peso', 'MXN', 2, '$'),
(null,'Mexico', 'Mexican Unidad de Inversion (UDI)', 'MXV', 2, NULL),
(null,'Micronesia', 'US Dollar', 'USD', 2, '$'),
(null,'Moldova', 'Moldovan Leu', 'MDL', 2, NULL),
(null,'Monaco', 'Euro', 'EUR', 2, '€'),
(null,'Mongolia', 'Tugrik', 'MNT', 2, NULL),
(null,'Montenegro', 'Euro', 'EUR', 2, '€'),
(null,'Montserrat', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Morocco', 'Moroccan Dirham', 'MAD', 2, ' .د.م '),
(null,'Mozambique', 'Mozambique Metical', 'MZN', 2, NULL),
(null,'Myanmar', 'Kyat', 'MMK', 2, NULL),
(null,'Namibia', 'Namibia Dollar', 'NAD', 2, NULL),
(null,'Namibia', 'Rand', 'ZAR', 2, NULL),
(null,'Nauru', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Nepal', 'Nepalese Rupee', 'NPR', 2, NULL),
(null,'Netherlands', 'Euro', 'EUR', 2, '€'),
(null,'New Caledonia', 'CFP Franc', 'XPF', 0, NULL),
(null,'New Zealand', 'New Zealand Dollar', 'NZD', 2, '$'),
(null,'Nicaragua', 'Cordoba Oro', 'NIO', 2, NULL),
(null,'Niger', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Nigeria', 'Naira', 'NGN', 2, '₦'),
(null,'Niue', 'New Zealand Dollar', 'NZD', 2, '$'),
(null,'Norfolk Island', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Northern Mariana Islands', 'US Dollar', 'USD', 2, '$'),
(null,'Norway', 'Norwegian Krone', 'NOK', 2, 'kr'),
(null,'Oman', 'Rial Omani', 'OMR', 3, NULL),
(null,'Pakistan', 'Pakistan Rupee', 'PKR', 2, 'Rs'),
(null,'Palau', 'US Dollar', 'USD', 2, '$'),
(null,'Panama', 'Balboa', 'PAB', 2, NULL),
(null,'Panama', 'US Dollar', 'USD', 2, '$'),
(null,'Papua New Guinea', 'Kina', 'PGK', 2, NULL),
(null,'Paraguay', 'Guarani', 'PYG', 0, NULL),
(null,'Peru', 'Sol', 'PEN', 2, 'S'),
(null,'Philippines', 'Philippine Peso', 'PHP', 2, '₱'),
(null,'Pitcairn', 'New Zealand Dollar', 'NZD', 2, '$'),
(null,'Poland', 'Zloty', 'PLN', 2, 'zł'),
(null,'Portugal', 'Euro', 'EUR', 2, '€'),
(null,'Puerto Rico', 'US Dollar', 'USD', 2, '$'),
(null,'Qatar', 'Qatari Rial', 'QAR', 2, NULL),
(null,'Réunion', 'Euro', 'EUR', 2, '€'),
(null,'Romania', 'Romanian Leu', 'RON', 2, 'lei'),
(null,'Russian Federation', 'Russian Ruble', 'RUB', 2, '₽'),
(null,'Rwanda', 'Rwanda Franc', 'RWF', 0, NULL),
(null,'Saint Barthélemy', 'Euro', 'EUR', 2, '€'),
(null,'Saint Helena, Ascension And Tristan Da Cunha', 'Saint Helena Pound', 'SHP', 2, NULL),
(null,'Saint Kitts And Nevis', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Saint Lucia', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Saint Martin (French Part)', 'Euro', 'EUR', 2, '€'),
(null,'Saint Pierre And Miquelon', 'Euro', 'EUR', 2, '€'),
(null,'Saint Vincent And The Grenadines', 'East Caribbean Dollar', 'XCD', 2, NULL),
(null,'Samoa', 'Tala', 'WST', 2, NULL),
(null,'San Marino', 'Euro', 'EUR', 2, '€'),
(null,'Sao Tome And Principe', 'Dobra', 'STN', 2, NULL),
(null,'Saudi Arabia', 'Saudi Riyal', 'SAR', 2, NULL),
(null,'Senegal', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Serbia', 'Serbian Dinar', 'RSD', 2, NULL),
(null,'Seychelles', 'Seychelles Rupee', 'SCR', 2, NULL),
(null,'Sierra Leone', 'Leone', 'SLL', 2, NULL),
(null,'Singapore', 'Singapore Dollar', 'SGD', 2, '$'),
(null,'Sint Maarten (Dutch Part)', 'Netherlands Antillean Guilder', 'ANG', 2, NULL),
(null,'Sistema Unitario De Compensacion Regional De Pagos \"sucre\"\"\"', 'Sucre', 'XSU', 0, NULL),
(null,'Slovakia', 'Euro', 'EUR', 2, '€'),
(null,'Slovenia', 'Euro', 'EUR', 2, '€'),
(null,'Solomon Islands', 'Solomon Islands Dollar', 'SBD', 2, NULL),
(null,'Somalia', 'Somali Shilling', 'SOS', 2, NULL),
(null,'South Africa', 'Rand', 'ZAR', 2, 'R'),
(null,'South Sudan', 'South Sudanese Pound', 'SSP', 2, NULL),
(null,'Spain', 'Euro', 'EUR', 2, '€'),
(null,'Sri Lanka', 'Sri Lanka Rupee', 'LKR', 2, 'Rs'),
(null,'Sudan (the)', 'Sudanese Pound', 'SDG', 2, NULL),
(null,'Suriname', 'Surinam Dollar', 'SRD', 2, NULL),
(null,'Svalbard And Jan Mayen', 'Norwegian Krone', 'NOK', 2, NULL),
(null,'Sweden', 'Swedish Krona', 'SEK', 2, 'kr'),
(null,'Switzerland', 'Swiss Franc', 'CHF', 2, NULL),
(null,'Switzerland', 'WIR Euro', 'CHE', 2, NULL),
(null,'Switzerland', 'WIR Franc', 'CHW', 2, NULL),
(null,'Syrian Arab Republic', 'Syrian Pound', 'SYP', 2, NULL),
(null,'Taiwan', 'New Taiwan Dollar', 'TWD', 2, NULL),
(null,'Tajikistan', 'Somoni', 'TJS', 2, NULL),
(null,'Tanzania, United Republic Of', 'Tanzanian Shilling', 'TZS', 2, NULL),
(null,'Thailand', 'Baht', 'THB', 2, '฿'),
(null,'Timor-leste', 'US Dollar', 'USD', 2, '$'),
(null,'Togo', 'CFA Franc BCEAO', 'XOF', 0, NULL),
(null,'Tokelau', 'New Zealand Dollar', 'NZD', 2, '$'),
(null,'Tonga', 'Pa’anga', 'TOP', 2, NULL),
(null,'Trinidad And Tobago', 'Trinidad and Tobago Dollar', 'TTD', 2, NULL),
(null,'Tunisia', 'Tunisian Dinar', 'TND', 3, NULL),
(null,'Turkey', 'Turkish Lira', 'TRY', 2, '₺'),
(null,'Turkmenistan', 'Turkmenistan New Manat', 'TMT', 2, NULL),
(null,'Turks And Caicos Islands', 'US Dollar', 'USD', 2, '$'),
(null,'Tuvalu', 'Australian Dollar', 'AUD', 2, NULL),
(null,'Uganda', 'Uganda Shilling', 'UGX', 0, NULL),
(null,'Ukraine', 'Hryvnia', 'UAH', 2, '₴'),
(null,'United Arab Emirates', 'UAE Dirham', 'AED', 2, 'د.إ'),
(null,'United Kingdom Of Great Britain And Northern Ireland', 'Pound Sterling', 'GBP', 2, '£'),
(null,'United States Minor Outlying Islands', 'US Dollar', 'USD', 2, '$'),
(null,'United States Of America', 'US Dollar', 'USD', 2, '$'),
(null,'United States Of America', 'US Dollar (Next day)', 'USN', 2, NULL),
(null,'Uruguay', 'Peso Uruguayo', 'UYU', 2, NULL),
(null,'Uruguay', 'Uruguay Peso en Unidades Indexadas (UI)', 'UYI', 0, NULL),
(null,'Uruguay', 'Unidad Previsional', 'UYW', 4,NULL),
(null,'Uzbekistan', 'Uzbekistan Sum', 'UZS', 2, NULL),
(null,'Vanuatu', 'Vatu', 'VUV', 0, NULL),
(null,'Venezuela', 'Bolívar Soberano', 'VES', 2, NULL),
(null,'Vietnam', 'Dong', 'VND', 0, '₫'),
(null,'Virgin Islands (British)', 'US Dollar', 'USD', 2, '$'),
(null,'Virgin Islands (U.S.)', 'US Dollar', 'USD', 2, '$'),
(null,'Wallis And Futuna', 'CFP Franc', 'XPF', 0, NULL),
(null,'Western Sahara', 'Moroccan Dirham', 'MAD', 2, NULL),
(null,'Yemen', 'Yemeni Rial', 'YER', 2, NULL),
(null,'Zambia', 'Zambian Kwacha', 'ZMW', 2, NULL),
(null,'Zimbabwe', 'Zimbabwe Dollar', 'ZWL', 2, NULL);

